version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "mambaforge-23.11"
conda:
    environment: doc/environment.yml
python:
    install:
        - method: pip
          path: .
submodules:
    include: all
    recursive: true
sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false
formats:
  - pdf
  - epub