version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install scikit-build-core nanobind

python:
  install:
    - method: pip
      path: .

conda:
  environment: doc/environment.yml

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub