# Copyright (c) 2022-2026, Yongchao Wu in Aalto University
# This file is from the mdapy project, released under the BSD 3-Clause License.
"""
Reference fixtures for ``build_crystal``: every structure mdapy supports is
also generated by atomsk's ``--create`` command and the canonical
(box, atoms, elements) tuple is committed under
``tests/fixtures/build_crystal/``. The actual test
(``tests/test_build_crystal.py``) does not need atomsk at runtime.

Run manually whenever a structure definition changes (or atomsk is
upgraded):

    python tests/_generate_fixtures/generate_build_crystal.py

Requires:
    - atomsk binary at ATOMSK_BIN
    - mdapy installed (only used to read the produced LAMMPS data files)
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))

import mdapy as mp                                              # noqa: E402

ATOMSK_BIN = os.environ.get(
    "ATOMSK_BIN",
    "/u/22/wuy33/unix/Study/atomsk/src/atomsk",
)
OUT_DIR = HERE.parent / "fixtures" / "build_crystal"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def _run_atomsk(structure: str, lattice_args, species, outfile: Path):
    """Invoke atomsk to write a LAMMPS data file. ``lattice_args`` is a
    list of strings appended after ``--create <structure>`` — typically
    ``[a]`` for cubic or ``[a, c]`` for hexagonal/tetragonal."""
    cmd = [ATOMSK_BIN, "--create", structure,
           *[str(x) for x in lattice_args],
           *species,
           str(outfile), "lammps"]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(
            f"atomsk failed: {' '.join(cmd)}\nstdout:\n{res.stdout}\n"
            f"stderr:\n{res.stderr}"
        )


def _read_canonical(lmp_path: Path):
    """Read a LAMMPS data file and return a canonical
    ``(box, sorted_positions, sorted_elements)`` triple — positions are
    rounded to 6 decimals before lex-sorting so tiny numerical noise
    (~1e-16) cannot flip rows that share an axis value with one
    implementation and not the other."""
    s = mp.System(str(lmp_path))
    pos = s.data.select("x", "y", "z").to_numpy()
    elements = s.data["element"].to_list() if "element" in s.data.columns \
               else [None] * s.N
    # Round to 6 decimals for sort key only; original positions are kept.
    key = np.round(pos, 6)
    order = np.lexsort((key[:, 2], key[:, 1], key[:, 0]))
    return s.box.box.copy(), pos[order], [elements[i] for i in order]


def _save_fixture(name: str, box, positions, elements):
    """Persist a canonical reference for one structure call."""
    np.savez_compressed(
        OUT_DIR / f"{name}.npz",
        box=np.asarray(box, dtype=np.float64),
        positions=np.asarray(positions, dtype=np.float64),
        elements=np.asarray(elements, dtype="<U4"),
    )


# ---------------------------------------------------------------------------
# Catalog: (fixture name, structure, atomsk-args, mdapy-call kwargs)
# ---------------------------------------------------------------------------

# For mdapy we always pass the same `name` and `structure`; the only thing
# that varies is whether we provide `c=` (hexagonal) or just `a=`.
CATALOG = [
    # CUBIC, single species (compat with the existing reference)
    ("Cu_fcc",      "fcc",        ["3.615"],                 ["Cu"],
     dict(structure="fcc", a=3.615), "Cu"),
    ("Fe_bcc",      "bcc",        ["2.83"],                  ["Fe"],
     dict(structure="bcc", a=2.83),  "Fe"),
    ("C_diamond",   "diamond",    ["3.6"],                   ["C"],
     dict(structure="diamond", a=3.6), "C"),
    ("W_sc",        "sc",         ["3.16"],                  ["W"],
     dict(structure="sc", a=3.16),  "W"),

    # CUBIC, two species
    ("NaCl_rocksalt", "rocksalt", ["5.64"],                  ["Na", "Cl"],
     dict(structure="rocksalt", a=5.64), ("Na", "Cl")),
    ("NiAl_cscl",   "cscl",       ["2.86"],                  ["Ni", "Al"],
     dict(structure="cscl", a=2.86), ("Ni", "Al")),
    ("GaAs_zb",     "zincblende", ["5.65"],                  ["Ga", "As"],
     dict(structure="zincblende", a=5.65), ("Ga", "As")),
    ("CaF2_fluorite", "fluorite", ["5.46"],                  ["Ca", "F"],
     dict(structure="fluorite", a=5.46), ("Ca", "F")),
    ("Ni3Al_l1_2",  "L1_2",       ["3.57"],                  ["Ni", "Al"],
     dict(structure="l1_2", a=3.57), ("Ni", "Al")),

    # CUBIC, three species
    ("SrTiO3_perovskite", "perovskite", ["3.905"],           ["Ti", "Sr", "O"],
     dict(structure="perovskite", a=3.905), ("Ti", "Sr", "O")),

    # HEXAGONAL, single + two species
    ("Mg_hcp",       "hcp",       ["3.21", "5.21304"],       ["Mg"],
     dict(structure="hcp", a=3.21, c=5.21304), "Mg"),
    ("GaN_wurtzite", "wurtzite",  ["3.19", "5.18"],          ["Ga", "N"],
     dict(structure="wurtzite", a=3.19, c=5.18), ("Ga", "N")),
    ("C_graphite",   "graphite",  ["2.46", "6.71"],          ["C"],
     dict(structure="graphite", a=2.46, c=6.71), "C"),
    # Lonsdaleite (hexagonal diamond) — generated via wurtzite + single C.
    ("C_lonsdaleite", "wurtzite", ["2.51", "4.12"],          ["C", "C"],
     dict(structure="lonsdaleite", a=2.51, c=4.12), "C"),
    # Single-layer graphene (mdapy-only — atomsk has no graphene mode,
    # so we generate a 1-layer graphite slab and drop the upper-layer
    # atoms in the fixture step). Skipped from the catalog; covered by
    # an mdapy-internal positional smoke test instead.
]


# ---------------------------------------------------------------------------
# Miller-orientation sweep — one reference per (structure, miller-set)
# ---------------------------------------------------------------------------

# atomsk --create ... orient hkl1 hkl2 hkl3 — only cubic.
MILLER_CATALOG = [
    # name, structure, atomsk-args, species, miller, mdapy-call
    ("Cu_fcc_111",  "fcc", ["3.615"], ["Cu"],
     ("[1-10]", "[11-2]", "[111]"),
     dict(structure="fcc", a=3.615,
          miller1=(1, -1, 0), miller2=(1, 1, -2), miller3=(1, 1, 1)),
     "Cu"),
    ("Fe_bcc_111",  "bcc", ["2.83"],  ["Fe"],
     ("[121]", "[-101]", "[1-11]"),
     dict(structure="bcc", a=2.83,
          miller1=(1, 2, 1), miller2=(-1, 0, 1), miller3=(1, -1, 1)),
     "Fe"),
    ("NaCl_rocksalt_111", "rocksalt", ["5.64"], ["Na", "Cl"],
     ("[1-10]", "[11-2]", "[111]"),
     dict(structure="rocksalt", a=5.64,
          miller1=(1, -1, 0), miller2=(1, 1, -2), miller3=(1, 1, 1)),
     ("Na", "Cl")),
    # HEXAGONAL Miller (4-index [hkil])
    ("Mg_hcp_prismatic", "hcp", ["3.21", "5.21"], ["Mg"],
     ("[1-100]", "[11-20]", "[0001]"),
     dict(structure="hcp", a=3.21, c=5.21,
          miller1=(1, -1, 0, 0), miller2=(1, 1, -2, 0), miller3=(0, 0, 0, 1)),
     "Mg"),
    ("GaN_wurtzite_prismatic", "wurtzite", ["3.19", "5.18"], ["Ga", "N"],
     ("[1-100]", "[11-20]", "[0001]"),
     dict(structure="wurtzite", a=3.19, c=5.18,
          miller1=(1, -1, 0, 0), miller2=(1, 1, -2, 0), miller3=(0, 0, 0, 1)),
     ("Ga", "N")),
]


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main():
    if not Path(ATOMSK_BIN).exists():
        raise SystemExit(f"atomsk binary not found at {ATOMSK_BIN}")

    print(f"Writing fixtures to {OUT_DIR}")

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)

        # Plain (non-Miller) catalog
        for fixture_name, atomsk_struct, lattice_args, species, _kw, _names in CATALOG:
            out = td / f"{fixture_name}.lmp"
            _run_atomsk(atomsk_struct, lattice_args, species, out)
            box, pos, ele = _read_canonical(out)
            _save_fixture(fixture_name, box, pos, ele)
            print(f"  ✓ {fixture_name}: {len(pos)} atoms")

        # Miller catalog
        for (fixture_name, atomsk_struct, lattice_args, species,
             miller, _kw, _names) in MILLER_CATALOG:
            out = td / f"{fixture_name}.lmp"
            cmd = [ATOMSK_BIN, "--create", atomsk_struct,
                   *[str(x) for x in lattice_args],
                   *species,
                   "orient", *miller,
                   str(out), "lammps"]
            res = subprocess.run(cmd, capture_output=True, text=True)
            if res.returncode != 0:
                raise RuntimeError(
                    f"atomsk failed:\n{' '.join(cmd)}\n{res.stderr}"
                )
            box, pos, ele = _read_canonical(out)
            _save_fixture(fixture_name, box, pos, ele)
            print(f"  ✓ {fixture_name} (miller): {len(pos)} atoms")


if __name__ == "__main__":
    main()
